version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend:
    build:
      context: ./SalesEventConsumer
      dockerfile: Dockerfile
    container_name: sales-event-consumer
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:5000  # Permite que o backend escute em todas as interfaces
    ports:
      - "5000:5000"
      - "5001:5001"

  frontend:
    build:
      context: ./sales-monitoring-ui
      dockerfile: Dockerfile
    container_name: sales-monitoring-ui
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:5000 # Ajusta a URL do backend
    ports:
      - "3000:80"
