version: '3.8'

networks:
  ambev_network:
    external: true 

services:
  backend:
    build:
      context: ./SalesEventConsumer
      dockerfile: Dockerfile
    container_name: sales-event-consumer
    environment:
      - RABBITMQ_HOST=rabbitmq
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - ambev_network

  frontend:
    build:
      context: ./SalesMonitorUI
      dockerfile: Dockerfile
    networks:
      - ambev_network
    ports:
      - "3000:80"
    restart: unless-stopped
